config/routes.rb
Nature::Application.routes.draw do
  resources :photos

  resources :albums

  resources :articles

  devise_for :users

  resources :users
  resources :homepage
  root :to => "homepage#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :photos
	belongs_to :user
  attr_accessible :article_name, :description, :user_id, :image
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :article
  attr_accessible :article_id, :name, :image, :remote_image_url, :photo
  mount_uploader :image, ImageUploader

  before_create :default_name

  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name, :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
require 'carrierwave'
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create


    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	
end

app/controllers/photos_controller.rb
require 'carrierwave'
class PhotosController < ApplicationController
   # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new(:article_id => params[:article_id])
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.create(params[:photo])
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      redirect_to @photo.article, notice: 'Photo was successfully updated.' 
    else
      render :edit
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url, notice: "Photo was successfully destroyed."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <%= f.input :article_name %>
  <%= f.input :description %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/_photo.html.erb
<div class="photo">
  <%= link_to image_tag(photo.image_url(:thumb)) %>
  <div class="name"><%= photo.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_photo_path(photo) %> |
    <%= link_to "remove", photo, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/articles/backup.index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

  <tbody>
    <% @articles.each do |article| %>
      <%= accordion do |accordion| %>
        <%= accordion.pane article.article_name do %>
          <table class="table table-striped">
            <tr>
              <td><%= link_to article.id, article_path(article) %></td>
              <td><%= article.article_name %></td>
              <td><%= article.description %></td>
              <td><%= article.user_id %></td>
              <td><%=l article.created_at %></td>
              <td>
                <%# article.photos.each do |photo| %>
                  <%= link_to image_tag(article.photos.first.image_url(:thumb)) %>
                <%# end %>
              </td>  
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_article_path(article), :class => 'btn btn-mini' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            article_path(article),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-mini btn-danger' %>
              </td>
            </tr>     
          </table>
        <% end %>
      <% end %>
    <% end %>
  </tbody>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

<% @articles.each do |article| %>
<ul class="nav nav-tabs">
  <li><a href="#link" data-toggle="tab"><%= article.id %></a></li>
  <li><a href="#name" data-toggle="tab"><%= article.article_name %></a></li>
  <li><a href="#description" data-toggle="tab">Description</a></li>
  <li><a href="#photo" data-toggle="tab">Photo</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="link"><%= link_to article.id, article_path(article) %></div>
  <div class="tab-pane active" id="name"><%= article.article_name %></div>
  <div class="tab-pane" id="description"><%= article.description %></div>
  <div class="tab-pane" id="photo"><%= link_to image_tag(article.photos.first.image_url(:thumb)) %></div>
</div>
    <% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">

  <tbody>
    <% @articles.each do |article| %>
      <dl>
        <dd><%= link_to article.id, article_path(article) %></dd>
        <dd><%= article.article_name %></dd>
        <dd><%= article.description %></dd>
        <dd><%= article.user_id %></dd>
        <dd><%=l article.created_at %></dd>
        <dd>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </dd>
      </dl>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:article_name) %>:</strong></dt>
  <dd><%= @article.article_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @article.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @article.user_id %></dd>
</dl>

<div id="photos">
  <% @article.photos.each do |photo| %>
  <%= render photo %>
 <% end %> 
</div>
<div class="clear"></div>

<%= form_for Photo.new do |f| %>
  <%= f.hidden_field :article_id, :value => @article.id %>
  <%= f.label :image, "Upload photos:" %>
  <%= f.file_field :image, multiple: true, name: "photo[image]" %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<div class="form-actions">
  <%= link_to t('.new', :default => t("helpers.links.add_photo")),
              new_photo_path(:article_id => @article), :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy_article")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/homepage/index.html.erb
<section id="carousel">
  <div class="page-header">
    <h1>Landscapes Carousel </h1>
  </div>

<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "1.jpg" %>
      <div class="carousel-caption">
        <h4>Forest in fog</h4>
        <p>Forest landsckape</p>
      </div>
    </div>
    <div class="item">
     <%= image_tag "2.jpg" %>
      <div class="carousel-caption">
        <h4>Waterfall</h4>
        <p>Waterfall landsckape.</p>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Camping" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">OfficeApp</a>     
          <div class="container nav-collapse">
            <ul class="nav">
              
                <li><%= link_to "Camping", articles_path  %></li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>  ">
        <button type="button" class="close" data-dismiss="alert">×</button>
          <%= msg %>
        </div>
      <% end %>

      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Accaunt control panel</li>

                      <% if user_signed_in? %>
                        <li>Logged in as <strong><%= current_user.email %></strong>.</li>
                        <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                        <li><%= link_to "Sign up(create new employe)", new_user_registration_path %></li>
                      <% else %>
                        <li> Please sign in </li>
                        <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
                    
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>Camping 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for @photo, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.hidden_field :article_id %>
  <%= f.input :name %>
  <%= f.input :image %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                photos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="photo">
  <%= link_to image_tag(photo.image_url(:thumb)) %>
  <div class="name"><%= photo.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_photo_path(photo) %> |
    <%= link_to "remove", photo, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/photos/create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload photo: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#photos").append("<%= j render(@photo) %>");
<% end %>

app/views/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/index.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:article_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.id, photo_path(photo) %></td>
        <td><%= photo.article_id %></td>
        <td><%= photo.name %></td>
        <td><%= photo.image %></td>
        <td><%=l photo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_photo_path(photo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      photo_path(photo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_photo_path,
            :class => 'btn btn-primary' %>

app/views/photos/new.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/photos/show.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:article_id) %>:</strong></dt>
  <dd><%= @photo.article_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @photo.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @photo.image %></dd>
  <p><%= image_tag @photo.image_url %></p>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              photos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_photo_path(@photo), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              photo_path(@photo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>